//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        public int ProductID { get; set; }

        [Display(Name = "Product name")]
        [Required]
        public string Name { get; set; }

        [Display(Name = "Category")]
        [Required]
        public int CategoryID { get; set; }

        [Required]
        public string Price { get; set; }

        public string Photo { get; set; }

        [Display(Name = "User")]
        [Required]
        public int UserID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }

        [Required(ErrorMessage = "Please, upload product's photo")]
        [NotMapped]
        public HttpPostedFileBase PhotoFile { get; set; }
    }
}
